---
- hosts: localhost
  connection: local
  tasks:
          - name: Create a resource group
            azure_rm_resourcegroup:
                    name: "{{ resource_group }}"
                    location: "{{ location }}"
                    state: present
