---
- hosts: localhost
  connection: local
  tasks:
          - name: Create a resource group
            azure_rm_resourcegroup:
                    name: washingtonprod
                    location: eastus
                    state: present
