- hosts: localhost
  connection: local
  vars:
    app_name: myTestApp
    location: eastus
    linux_plan_name: myTestPlan
    traffic_manager_profile_name: myTMProfile
    traffic_manager_endpoint_name: endpoint1

  roles:
    - azure.azure_preview_modules

  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group_name }}"
      location: "{{ location }}"

  - name: Create resource group for app service plan
    azure_rm_resourcegroup:
      name: "{{ resource_group_name }}2nd"
      location: "{{ location }}"

  - name: Create App Service Plan
    azure_rm_appserviceplan:
      resource_group: "{{ resource_group_name }}2nd"
      name: "{{ linux_plan_name }}"
      location: "{{ location }}"
      is_linux: true
      sku: S1
      number_of_workers: 1

  - name: Create a Linux web app with Java framework and Tomcat
    azure_rm_webapp:
      resource_group: "{{ resource_group_name }}"
      name: "{{ app_name }}"
      plan:
        resource_group: "{{ resource_group_name }}2nd"
        name: "{{ linux_plan_name }}"
      app_settings:
        testkey: "testvalue"
      frameworks:
        - name: java
          version: 8
          settings:
            java_container: "Tomcat"
            java_container_version: "8.5"